package Interfaz;


import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

import java.sql.DriverManager;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.ResultSet;


import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Rodrigo Carcamo, Eduardo Figueroa, Thais caamaño, Lucia Gomez
 * @version 24/11/2024
 */



public class AdminFrame extends javax.swing.JFrame {

    private int xMouse, yMouse;
    public AdminFrame() {
        
        
        //Color de fondo
        Color cfondo = new Color(29,29,33); 
        getContentPane().setBackground(cfondo);
        initComponents();
        cargarDatosEnTabla();
        
        

        
        
        jTable1.setOpaque(true);
        jTable1.setBackground(Color.CYAN);
        
        //Color de fondo de la Tabla
        jTable1.setBackground(new java.awt.Color(1,29,33));
        
        
        
        //Crear el evento para conseguir xMouse y yMouse por un MouseEvent
        addMouseListener(new MouseAdapter(){
        public void mousePressed(MouseEvent e){
        xMouse = e.getX();
        yMouse = e.getY();

        }
    });
        
        //Metodo para el movimiento en tiempo real
        addMouseMotionListener(new MouseAdapter() {
        public void mouseDragged(MouseEvent e) {
            // Actualizar el movimiento de la ventana
            int x = e.getXOnScreen();
            int y = e.getYOnScreen();
            setLocation(x - xMouse, y - yMouse);
        }
    });
        
    }
    
    //lista para guardar y asi facilitar el manejo de informacion
    public static List<Producto> productos = new ArrayList<>();
    
    
    
        private void cargarDatosEnTabla() {
        // Modelo de la tabla
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        // Limpiar la tabla antes de cargar datos
        modelo.setRowCount(0);

        // Conexión a la base de datos
        String url = "jdbc:mysql://javaproyecto.c4twvuokhnt7.us-east-1.rds.amazonaws.com:3306/PROYECTO_JAVA";
        String usuario = "admin";
        String contraseña = "javaproyecto1";

        String consulta = "SELECT * FROM PROYECTO_JAVA.PRODUCTO";

        try (Connection conexion = DriverManager.getConnection(url, usuario, contraseña);
             Statement stmt = conexion.createStatement();
             ResultSet rs = stmt.executeQuery(consulta)) {

            // Recorrer los resultados y agregar las filas al modelo
            while (rs.next()) {
                String nombre = rs.getString("nombre_producto");
                int stock = rs.getInt("stock");
                int precio = rs.getInt("precio");

                // Agregar fila al modelo
                modelo.addRow(new Object[]{ nombre, stock, precio});
            }

        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al cargar los datos: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_exit2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtn_anadir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn_exit2.setBackground(new java.awt.Color(38, 34, 41));
        jbtn_exit2.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_exit2.setText("X");
        jbtn_exit2.setBorder(null);
        jbtn_exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_exit2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 30, 20));

        jTable1.setBackground(new java.awt.Color(29, 29, 33));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Stock", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(204, 255, 204));
        jTable1.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 720, 510));

        jbtn_anadir.setBackground(new java.awt.Color(111, 157, 228));
        jbtn_anadir.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_anadir.setText("Añadir");
        jbtn_anadir.setBorder(null);
        jbtn_anadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_anadirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_anadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 120, 50));

        jButton1.setBackground(new java.awt.Color(111, 157, 228));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 120, 50));

        jButton2.setBackground(new java.awt.Color(111, 157, 228));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 120, 50));

        jButton3.setBackground(new java.awt.Color(111, 157, 228));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("recargar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_exit2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtn_exit2ActionPerformed

    private void jbtn_anadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_anadirActionPerformed
        Frm_Anadir add = new Frm_Anadir();
        add.setVisible(true);
        
    }//GEN-LAST:event_jbtn_anadirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Frm_borrar borrar = new Frm_borrar();
            borrar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            Frm_actualizar act = new Frm_actualizar();
            act.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cargarDatosEnTabla();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn_anadir;
    private javax.swing.JButton jbtn_exit2;
    // End of variables declaration//GEN-END:variables
}
