
package Interfaz;

import Controlador.Registro;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo Carcamo, Eduardo Figueroa, Thais caamaño, Lucia Gomez
 */
public class Frm_borrar extends javax.swing.JFrame {

    
    
    
    public Frm_borrar() {
        //ajustar el color del fondo
        Color cfondo = new Color(29,29,33); 
        getContentPane().setBackground(cfondo);
        
        
        initComponents();
        
        
        
     
        
    }
    
    
    private void borrarProducto() {
        // Obtener el texto del campo de entrada
        String textoIngresado = jtxt_eliminar.getText().trim();

        // Verificar si el campo está vacío
        if (textoIngresado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;  // No continuar si el campo está vacío
        }

        try {
            // Intentar convertir el texto ingresado en un número entero (ID del producto)
            int id = Integer.parseInt(textoIngresado);

            // Confirmación antes de proceder con la eliminación
            int opcion = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar este producto?", "Eliminar", JOptionPane.YES_NO_OPTION);

            if (opcion == JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(null, "Producto eliminado", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
                // Aquí puedes llamar a tu método para eliminar el producto usando el ID
            } else {
                JOptionPane.showMessageDialog(null, "Producto no eliminado", "Eliminar", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (NumberFormatException e) {
            // Si el texto no es un número válido, mostrar un mensaje de error
            JOptionPane.showMessageDialog(this, "El ID ingresado no es válido. Por favor, ingrese un número.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jtxt_eliminar = new javax.swing.JTextField();
        jbtn_borrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Borrar");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Borrar Producto");

        jtxt_eliminar.setBackground(new java.awt.Color(38, 34, 41));
        jtxt_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_eliminar.setBorder(null);

        jbtn_borrar.setBackground(new java.awt.Color(230, 92, 92));
        jbtn_borrar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_borrar.setText("Borrar");
        jbtn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jtxt_eliminar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jbtn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxt_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbtn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrarActionPerformed
        // TODO add your handling code here:
        String nombre;
        nombre = this.jtxt_eliminar.getText();
        
        Registro reg = new Registro();
        
        int opcion = JOptionPane.showConfirmDialog(this, "Seguro que desea Eliminar?","Eliminar",0);
        
        if (opcion == 0) {
            reg.borrar(nombre);
            JOptionPane.showMessageDialog(null, "Producto eliminado", "Eliminar", 1);
        }
        else{
            JOptionPane.showMessageDialog(null, "Producto No eliminado", "Eliminar", 2);
        }
    }//GEN-LAST:event_jbtn_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtn_borrar;
    private javax.swing.JTextField jtxt_eliminar;
    // End of variables declaration//GEN-END:variables
}
