/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Controlador.Registro;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import Interfaz.Producto;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo Carcamo, Eduardo Figueroa, Thais caamaño, Lucia Gomez
 */
public class Frm_actualizar extends javax.swing.JFrame {

   Registro reg = new Registro();
    
    
    public Frm_actualizar() {
        //ajustar el color del fondo
        Color cfondo = new Color(29,29,33); 
        getContentPane().setBackground(cfondo);
        
        
    
        initComponents();
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_nombre_producto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxt_stock = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxt_precio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jbtn_buscar = new javax.swing.JButton();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Actualizar");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Actualizar Producto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 6, -1, 48));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, 20));

        jtxt_nombre_producto.setBackground(new java.awt.Color(38, 34, 41));
        jtxt_nombre_producto.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_nombre_producto.setBorder(null);
        getContentPane().add(jtxt_nombre_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 176, 30));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stock");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jtxt_stock.setBackground(new java.awt.Color(38, 34, 41));
        jtxt_stock.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_stock.setBorder(null);
        getContentPane().add(jtxt_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 177, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jtxt_precio.setBackground(new java.awt.Color(38, 34, 41));
        jtxt_precio.setForeground(new java.awt.Color(255, 255, 255));
        jtxt_precio.setBorder(null);
        getContentPane().add(jtxt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 180, 30));

        jButton1.setBackground(new java.awt.Color(111, 157, 228));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 90, 30));

        jbtn_buscar.setBackground(new java.awt.Color(111, 157, 228));
        jbtn_buscar.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jbtn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_buscar.setText("Buscar");
        jbtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 70, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
        // TODO add your handling code here:
        String nombre =this.jtxt_nombre_producto.getText();

        Producto producto = reg.buscarPornombre(nombre);
        //rescato los datos del objeto producto
        String nombre_producto = producto.getNombre();
        int stock = producto.getStock();
        double precio = producto.getPrecio();
        
        //pasar estas variables anteriores a los textos de cada texfield de la ventana
        this.jtxt_nombre_producto.setText(nombre_producto);
        this.jtxt_stock.setText(String.valueOf(stock));
        this.jtxt_precio.setText(String.valueOf(precio));
        
    }//GEN-LAST:event_jbtn_buscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String nombre;
        int stock;
        double precio;
        
        
        nombre = this.jtxt_nombre_producto.getText();
        stock=Integer.parseInt(this.jtxt_stock.getText());
        precio=Integer.parseInt(this.jtxt_precio.getText());
        
        Producto producto = new Producto(nombre,nombre, stock, precio);
        reg.actualizar(producto,nombre);
        
        JOptionPane.showMessageDialog(null, "Datos actualizados", "Actulizar", 2);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtn_buscar;
    private javax.swing.JTextField jtxt_nombre_producto;
    private javax.swing.JTextField jtxt_precio;
    private javax.swing.JTextField jtxt_stock;
    // End of variables declaration//GEN-END:variables
}
