package Interfaz;


import BD.Conexion;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rodrigo Carcamo, Eduardo Figueroa, Thais caamaño, Lucia Gomez
 * @version Profe hernan no me raje xfa
 *  */
public class LoginFrame extends javax.swing.JFrame {

    private int xMouse, yMouse;
    
 
    
    
    public LoginFrame() {
        
        
        
        
        
        setUndecorated(true); //Metodo para hacer solo el Frame
        initComponents();
        
        //Para que aparezca en el centro
        setLocationRelativeTo(null);
        
        Color cfondo = new Color(29,29,33); //Color de fondo
        getContentPane().setBackground(cfondo);
        
        
        //Crear el evento para conseguir xMouse y yMouse por un MouseEvent
        addMouseListener(new MouseAdapter(){
        public void mousePressed(MouseEvent e){
        xMouse = e.getX();
        yMouse = e.getY();

        }
    });
        
        //Metodo para el movimiento en tiempo real
        addMouseMotionListener(new MouseAdapter() {
        public void mouseDragged(MouseEvent e) {
            // Actualizar el movimiento de la ventana
            int x = e.getXOnScreen();
            int y = e.getYOnScreen();
            setLocation(x - xMouse, y - yMouse);
        }
    });
        
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_contrasena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtn_login = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtxt_Usuario1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion - Login");
        setBackground(new java.awt.Color(28, 29, 33));
        setMaximumSize(new java.awt.Dimension(618, 459));
        setMinimumSize(new java.awt.Dimension(618, 459));
        setPreferredSize(new java.awt.Dimension(618, 459));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 266, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 55, 107, 57));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese sus credenciales.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 130, 170, -1));

        jtxt_contrasena.setBackground(new java.awt.Color(38, 34, 41));
        jtxt_contrasena.setForeground(new java.awt.Color(140, 140, 148));
        jtxt_contrasena.setBorder(null);
        jtxt_contrasena.setCaretColor(new java.awt.Color(140, 140, 148));
        jtxt_contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_contrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 171, 32));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 178, -1, -1));

        jbtn_login.setBackground(new java.awt.Color(111, 157, 228));
        jbtn_login.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_login.setText("Login");
        jbtn_login.setBorder(null);
        jbtn_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jbtn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 149, 40));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 216, -1, -1));

        jButton1.setBackground(new java.awt.Color(111, 157, 228));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 0, 20, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 280, 460));

        jtxt_Usuario1.setBackground(new java.awt.Color(38, 34, 41));
        jtxt_Usuario1.setForeground(new java.awt.Color(140, 140, 148));
        jtxt_Usuario1.setBorder(null);
        jtxt_Usuario1.setCaretColor(new java.awt.Color(140, 140, 148));
        jtxt_Usuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_Usuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtxt_Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 216, 171, 32));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //Metodo para salir del programa
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_loginActionPerformed
        
            String usuario = this.jtxt_Usuario1.getText(); 
    String contrasena = this.jtxt_contrasena.getText();

    System.out.println("Usuario ingresado: " + usuario);
    System.out.println("Contraseña ingresada: " + contrasena);
    
    
    
    
    // Llamar a un método que verifique las credenciales en la base de datos
    if (verificarCredenciales(usuario, contrasena)) {
        // Si las credenciales son correctas
        JOptionPane.showMessageDialog(null, "Ingreso exitoso!");
        
        // Ocultar Login
        dispose();

        // Abrir el nuevo formulario (AdminFrame)
        AdminFrame admf = new AdminFrame();
        admf.setVisible(true);
    } else {
        // Si las credenciales no son correctas
        JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.");
    }
}  

// Método para verificar las credenciales en la base de datos
private boolean verificarCredenciales(String usuario, String contrasena) {
    boolean esValido = false;
    
    // Crear la consulta SQL
    String query = "SELECT * FROM ADMINISTRADOR WHERE nombre = ? AND contrasena = ?";
    
    // Conectar a la base de datos
    Connection conexion = Conexion.conectar();
    
    if (conexion != null) {
        try {
            // Usar PreparedStatement para prevenir SQL Injection
            PreparedStatement ps = conexion.prepareStatement(query);
            ps.setString(1, usuario);  // Establecer el valor del usuario
            ps.setString(2, contrasena); // Establecer el valor de la contraseña
            
            // Ejecutar la consulta
            ResultSet rs = ps.executeQuery();
            
            // Si encontramos una fila que coincide con el usuario y la contraseña
            if (rs.next()) {
                esValido = true; // Credenciales correctas
            }
            
            // Cerrar los recursos
            rs.close();
            ps.close();
            conexion.close();
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error al verificar las credenciales.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "No se pudo conectar a la base de datos.");
    }
    
    return esValido;

    }//GEN-LAST:event_jbtn_loginActionPerformed

    private void jtxt_contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_contrasenaActionPerformed

    private void jtxt_Usuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_Usuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_Usuario1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Llamada al método conectar() para establecer la conexión
        Connection conexion = Conexion.conectar();
        
        if (conexion != null) {
            System.out.println("Conexión exitosa");
            
            // Definir la consulta
            String query = "SELECT * FROM ADMINISTRADOR";
            System.out.println("Consulta: " + query);
            
            // Llamada al método para ejecutar la consulta
            Conexion.ejecutarConsulta(conexion, query);
            
        } else {
            System.out.println("No se pudo establecer la conexión");
        }
    
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtn_login;
    private javax.swing.JTextField jtxt_Usuario1;
    private javax.swing.JTextField jtxt_contrasena;
    // End of variables declaration//GEN-END:variables
}
